package com.xinwei.lotteryDb;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of user_balance.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserBalance implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户的UID. */
	private Long userId;

	/** 用户的电话号码. */
	private String telphonenum;

	/** 操作前余额. */
	private Double beginningbalance;

	/** 余额有效期. */
	private Date expiredata;

	/** 扩展余额信息. */
	private String balanceext;

	/** 事物号. */
	private String transaction;

	/** 最后更新时间. */
	private Date updatetime;

	/** 更新来源. */
	private String updatesource;

	/**
	 * Constructor.
	 */
	public UserBalance() {
	}

	/**
	 * Set the 用户的UID.
	 * 
	 * @param userId
	 *            用户的UID
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * Get the 用户的UID.
	 * 
	 * @return 用户的UID
	 */
	public Long getUserId() {
		return this.userId;
	}

	/**
	 * Set the 用户的电话号码.
	 * 
	 * @param telphonenum
	 *            用户的电话号码
	 */
	public void setTelphonenum(String telphonenum) {
		this.telphonenum = telphonenum;
	}

	/**
	 * Get the 用户的电话号码.
	 * 
	 * @return 用户的电话号码
	 */
	public String getTelphonenum() {
		return this.telphonenum;
	}

	/**
	 * Set the 操作前余额.
	 * 
	 * @param beginningbalance
	 *            操作前余额
	 */
	public void setBeginningbalance(Double beginningbalance) {
		this.beginningbalance = beginningbalance;
	}

	/**
	 * Get the 操作前余额.
	 * 
	 * @return 操作前余额
	 */
	public Double getBeginningbalance() {
		return this.beginningbalance;
	}

	/**
	 * Set the 余额有效期.
	 * 
	 * @param expiredata
	 *            余额有效期
	 */
	public void setExpiredata(Date expiredata) {
		this.expiredata = expiredata;
	}

	/**
	 * Get the 余额有效期.
	 * 
	 * @return 余额有效期
	 */
	public Date getExpiredata() {
		return this.expiredata;
	}

	/**
	 * Set the 扩展余额信息.
	 * 
	 * @param balanceext
	 *            扩展余额信息
	 */
	public void setBalanceext(String balanceext) {
		this.balanceext = balanceext;
	}

	/**
	 * Get the 扩展余额信息.
	 * 
	 * @return 扩展余额信息
	 */
	public String getBalanceext() {
		return this.balanceext;
	}

	/**
	 * Set the 事物号.
	 * 
	 * @param transaction
	 *            事物号
	 */
	public void setTransaction(String transaction) {
		this.transaction = transaction;
	}

	/**
	 * Get the 事物号.
	 * 
	 * @return 事物号
	 */
	public String getTransaction() {
		return this.transaction;
	}

	/**
	 * Set the 最后更新时间.
	 * 
	 * @param updatetime
	 *            最后更新时间
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * Get the 最后更新时间.
	 * 
	 * @return 最后更新时间
	 */
	public Date getUpdatetime() {
		return this.updatetime;
	}

	/**
	 * Set the 更新来源.
	 * 
	 * @param updatesource
	 *            更新来源
	 */
	public void setUpdatesource(String updatesource) {
		this.updatesource = updatesource;
	}

	/**
	 * Get the 更新来源.
	 * 
	 * @return 更新来源
	 */
	public String getUpdatesource() {
		return this.updatesource;
	}


}
